name: Regression Test

on:
  pull_request:
  push:
    branches-ignore:
      - 'dependabot/**'

jobs:
  regression:
    name: Regression test
    runs-on: ubuntu-latest
    environment: regression
    steps:
      - uses: actions/checkout@v6

      - name: Download corpus
        uses: k0staa/download-gdrive-file-action@v1.1
        with:
          service-account-key-json: ${{ secrets.SERVICE_ACCOUNT_KEY_JSON }}
          download-file-name: rar-corpus.zip

      - name: Unzip corpus
        run: unzip rar-corpus.zip

      - uses: actions/setup-java@v5
        with:
          java-version: '21'
          java-package: 'jdk'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Regression test
        id: regression
        env:
          JUNRAR_REGRESSION_TEST_CORPUS_ROOT: '${{ github.workspace }}/rar-corpus/'
          JUNRAR_REGRESSION_TEST_CORPUS_DIR: '${{ github.workspace }}/rar-corpus/'
        run: ./gradlew regressionTest

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: regression-test-results
          path: build/test-results/